# Generated by Django 5.1.4 on 2025-01-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollableBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the scrollable banner', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Image for the scrollable banner', null=True, upload_to='scrollable_banners/')),
                ('external_url', models.URLField(blank=True, help_text='External URL for the scrollable banner', null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority of the scrollable banner for ordering')),
                ('is_active', models.BooleanField(default=True, help_text='Is the scrollable banner active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the scrollable banner was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the scrollable banner was last updated')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the banner', max_length=255, null=True)),
                ('image', models.ImageField(help_text='Image for the banner', null=True, upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('CATEGORY', 'Category'), ('VENDOR', 'Vendor')], help_text='Type of banner: Promotional, Category, or Vendor', max_length=20)),
                ('external_url', models.URLField(blank=True, help_text='External URL for promotional banners', null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Priority of the banner for ordering')),
                ('is_active', models.BooleanField(default=True, help_text='Is the banner active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the banner was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the banner was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Linked category for the banner', null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('vendor', models.ForeignKey(blank=True, help_text='Linked vendor for the banner', null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetails')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
