# Generated by Django 5.1.4 on 2025-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='ScrollableBanner',
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
