# Generated by Django 5.1.4 on 2025-01-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Image for the banner', null=True, upload_to='banners/'),
        ),
    ]
