# Generated by Django 5.1.4 on 2025-01-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('hero', 'Hero'), ('grid', 'Grid'), ('scroll', 'scroll')], default='hero', help_text='Type of the banner (Hero, Grid, scrollbar)', max_length=10),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('scroll', 'Scroll')], default='top', help_text='Position of the banner on the page', max_length=20),
        ),
    ]
