# Generated by Django 5.1.4 on 2025-02-15 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_wishlist'),
        ('products', '0015_delete_bulkproductupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_review', to='products.product')),
            ],
        ),
    ]
