# Generated by Django 5.1.4 on 2025-01-24 08:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authusers', '0001_initial'),
        ('products', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the cart was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the cart was last updated.')),
                ('last_reminder_sent', models.DateTimeField(blank=True, help_text='The date and time when the last reminder email was sent.', null=True)),
                ('user', models.OneToOneField(help_text='The user associated with this cart.', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='The quantity of this product in the cart.')),
                ('added_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the item was added to the cart.')),
                ('cart', models.ForeignKey(help_text='The cart this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_orders.cart')),
                ('product_variant', models.ForeignKey(help_text='The specific product variant added to the cart.', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price of the order.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cod_pending', 'COD Pending'), ('cod_paid', 'COD Paid'), ('cancelled', 'Cancelled')], default='pending', help_text='Payment status for the order.', max_length=15)),
                ('order_status', models.CharField(choices=[('placed', 'Order Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='placed', help_text='Current status of the order.', max_length=15)),
                ('cod_remittance_date', models.DateField(blank=True, help_text='Date when COD payment was remitted.', null=True)),
                ('cod_payment_received', models.BooleanField(default=False, help_text='Indicates whether COD payment has been received.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.ForeignKey(blank=True, help_text='The address used for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='authusers.address')),
                ('customer', models.ForeignKey(help_text='The customer who placed the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_delivery_date', models.DateField()),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('overall_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='authusers.address')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='cart_orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The quantity of this product purchased.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product at the time of purchase.', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='Payment status for the order.', max_length=10)),
                ('order_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('packed', 'Packed'), ('warehouse', 'Warehouse'), ('shiped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='confirmed', help_text='Status of the order item.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this item was added to the order.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this item was last updated.')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart_orders.order')),
                ('product_variant', models.ForeignKey(help_text='The specific product variant purchased.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='products.productvariant')),
                ('vendor', models.ForeignKey(blank=True, help_text='The vendor associated with this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='vendors.vendordetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal for the vendor-specific items.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The main order this sub-order belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='cart_orders.order')),
                ('vendor', models.ForeignKey(help_text='The vendor associated with this sub-order.', on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='vendors.vendordetails')),
            ],
        ),
    ]
