# Generated by Django 5.1.4 on 2025-02-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_portal', '0002_initial'),
        ('cart_orders', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='order_item',
            field=models.ForeignKey(help_text='The order item for which the refund is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='cart_orders.orderitem'),
        ),
        migrations.AddField(
            model_name='refundmedia',
            name='refund',
            field=models.ForeignKey(help_text='The refund associated with this media', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='admin_portal.refund'),
        ),
        migrations.AddField(
            model_name='softdata',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soft_data', to='cart_orders.order'),
        ),
        migrations.AddField(
            model_name='vendorpayout',
            name='vendor',
            field=models.ForeignKey(help_text='Vendor receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='vendors.vendordetails'),
        ),
    ]
