# Generated by Django 5.1.4 on 2025-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetails',
            name='stored_images',
            field=models.JSONField(blank=True, help_text='Store exactly 4 image URLs or paths.', null=True),
        ),
    ]
