# Generated by Django 5.1.4 on 2025-01-25 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendordetails_stored_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendordetails',
            name='stored_images',
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_images', to='vendors.vendordetails')),
            ],
        ),
    ]
