# Generated by Django 5.1.4 on 2025-01-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_remove_vendordetails_stored_images_storeimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreImage',
        ),
    ]
