# Generated by Django 5.1.4 on 2025-01-27 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0005_storeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedEditionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_stock', models.PositiveIntegerField(help_text='Stock allocated specifically for Limited Edition')),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Start date for Limited Edition availability')),
                ('available_until', models.DateTimeField(help_text='End date for Limited Edition availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(help_text='The product being marked as Limited Edition', on_delete=django.db.models.deletion.CASCADE, related_name='limited_edition', to='products.product')),
                ('vendor', models.ForeignKey(help_text='Vendor who is setting the Limited Edition', on_delete=django.db.models.deletion.CASCADE, to='vendors.vendordetails')),
            ],
            options={
                'ordering': ['-available_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('available_from__lt', models.F('available_until'))), name='valid_limited_edition_dates')],
            },
        ),
    ]
