# Generated by Django 5.1.4 on 2025-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_limitededitionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banners',
            field=models.ImageField(blank=True, help_text='Banner image for the category', null=True, upload_to='category_banners/'),
        ),
    ]
