# Generated by Django 5.1.4 on 2025-01-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_details',
            field=models.JSONField(blank=True, help_text='Structured additional details for the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='common_description',
            field=models.TextField(blank=True, help_text='General description for the product', null=True),
        ),
    ]
