# Generated by Django 5.1.4 on 2025-01-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='common_description',
        ),
    ]
