# Generated by Django 5.1.4 on 2025-02-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_common_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product',)},
        ),
    ]
