# Generated by Django 5.1.4 on 2025-02-11 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, help_text='Unique SKU for the product variant size', max_length=14, unique=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Size-specific attributes')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.attributevalue')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.productvariant')),
            ],
        ),
    ]
