# Generated by Django 5.1.4 on 2025-02-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='ProductVariantSize',
        ),
    ]
