# Generated by Django 5.1.4 on 2025-02-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkProductUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bulk_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attributes',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='primary_attribute',
            field=models.ForeignKey(default=70, help_text='Primary attribute for this variant', on_delete=django.db.models.deletion.CASCADE, related_name='primary_variants', to='products.attributevalue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='secondary_attributes',
            field=models.ManyToManyField(blank=True, help_text='Additional attributes like size, fit, etc.', related_name='secondary_variants', to='products.attributevalue'),
        ),
    ]
