# Generated by Django 5.1.4 on 2025-02-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bulkproductupload_remove_productvariant_attributes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkProductUpload',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='primary_attribute',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='secondary_attributes',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.ManyToManyField(related_name='variants', to='products.attributevalue'),
        ),
    ]
